"""
Fragstats Adapter for CRAFTY GIS
Interfaces with Fragstats landscape ecology analysis tools via command line
"""
import subprocess
import logging
import os
import tempfile
from pathlib import Path
from typing import Dict, Any, Optional, List
import json
import csv

logger = logging.getLogger(__name__)

class FragstatsAdapter:
    """
    Adapter for interfacing with Fragstats landscape ecology analysis tools.
    Uses Fragstats command line interface for patch and landscape metrics.
    """

    def __init__(self):
        # In production, these would come from config/settings
        self.fragstats_path = os.environ.get("FRAGSTATS_PATH", "fragstats")

    async def calculate_landscape_metrics(
        self,
        classified_raster: str,
        parameters: Dict[str, Any] = None
    ) -> Dict[str, Any]:
        """
        Calculate landscape metrics using Fragstats.
        """
        if parameters is None:
            parameters = {}

        try:
            # Create temporary directory for Fragstats output
            output_dir = tempfile.mkdtemp()

            # Fragstats requires a parameter file
            param_file = os.path.join(output_dir, f"fragstats_params_{os.getpid()}.txt")
            output_file = os.path.join(output_dir, f"fragstats_output_{os.getpid()}.txt")

            # Create Fragstats parameter file
            self._create_fragstats_param_file(
                param_file,
                classified_raster,
                output_file,
                parameters
            )

            # Run Fragstats
            cmd = [
                self.fragstats_path,
                param_file
            ]

            logger.info(f"Executing Fragstats: {' '.join(cmd)}")
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=300  # 5 minute timeout for landscape analysis
            )

            if result.returncode != 0:
                logger.error(f"Fragstats failed: {result.stderr}")
                # Fragstats sometimes writes errors to stdout, so check both
                error_output = result.stderr if result.stderr else result.stdout
                raise Exception(f"Fragstats processing failed: {error_output}")

            # Parse Fragstats output
            metrics = self._parse_fragstats_output(output_file)

            return {
                "landscape_metrics": metrics,
                "classified_raster": classified_raster,
                "parameters_used": parameters,
                "output_file": output_file,
                "processing_log": result.stdout
            }

        except subprocess.TimeoutExpired:
            logger.error("Fragstats processing timed out")
            raise Exception("Fragstats process timed out")
        except Exception as e:
            logger.error(f"Error in Fragstats processing: {str(e)}")
            raise

    def _create_fragstats_param_file(
        self,
        param_file: str,
        classified_raster: str,
        output_file: str,
        parameters: Dict[str, Any]
    ):
        """
        Create a Fragstats parameter file.
        """
        # Fragstats parameter file format
        params = [
            "# Fragstats Parameter File - Generated by CRAFTY GIS",
            "",
            f"[INPUT]",
            f"FILENAME = {classified_raster}",
            f"FILE_FORMAT = 1",  # 1 = GeoTIFF (adjust based on actual format)
            f"CELL_SIZE = {parameters.get('cell_size', 30)}",  # Would extract from raster
            f"NUM_ROWS = {parameters.get('num_rows', 1000)}",  # Would extract from raster
            f"NUM_COLUMNS = {parameters.get('num_columns', 1000)}",  # Would extract from raster
            f"NUM_ORIENTATIONS = 8",
            f"BACKGROUND_VALUE = {parameters.get('background_value', 0)}",
            "",
            f"[OUTPUT]",
            f"FILENAME = {output_file}",
            f"OUTPUT_FORMAT = 1",  # 1 = ASCII
            f"SAVE_AREA_ESTIMATES = {(parameters.get('save_area_estimates', True))}",
            f"SAVE_PERIMETER_ESTIMATES = {(parameters.get('save_perimeter_estimates', True))}",
            f"SAVE_SHAPE_ESTIMATES = {(parameters.get('save_shape_estimates', True))}",
            f"SAVE_CORE_AREA_ESTIMATES = {(parameters.get('save_core_area_estimates', True))}",
            f"SAVE_CONTRAST_ESTIMATES = {(parameters.get('save_contrast_estimates', False))}",
            f"SAVE_SIMILARITY_ESTIMATES = {(parameters.get('save_similarity_estimates', False))}",
            f"SAVE_INTERSPERSION_ESTIMATES = {(parameters.get('save_interspersion_estimates', False))}",
            "",
            f"[METRICS]",
            f"CALCULATE_AREA_METRICS = {(parameters.get('calculate_area_metrics', True))}",
            f"CALCULATE_PERIMETER_METRICS = {(parameters.get('calculate_perimeter_metrics', True))}",
            f"CALCULATE_SHAPE_METRICS = {(parameters.get('calculate_shape_metrics', True))}",
            f"CALCULATE_CORE_AREA_METRICS = {(parameters.get('calculate_core_area_metrics', True))}",
            f"CALCULATE_CONTRAST_METRICS = {(parameters.get('calculate_contrast_metrics', False))}",
            f"CALCULATE_AGGREGATION_METRICS = {(parameters.get('calculate_aggregation_metrics', True))}",
            f"CALCULATE_DIVERSITY_METRICS = {(parameters.get('calculate_diversity_metrics', True))}",
            f"CALCULATE_INTERSPERSION_METRICS = {(parameters.get('calculate_interspersion_metrics', False))}",
            f"CALCULATE_PROXIMITY_METRICS = {(parameters.get('calculate_proximity_metrics', False))}",
            ""
        ]

        # Write parameter file
        with open(param_file, 'w') as f:
            f.write('\n'.join(params))

    def _parse_fragstats_output(self, output_file: str) -> Dict[str, Any]:
        """
        Parse Fragstats output file into structured metrics.
        """
        metrics = {
            "patch_metrics": {},
            "class_metrics": {},
            "landscape_metrics": {}
        }

        try:
            with open(output_file, 'r') as f:
                lines = f.readlines()

            current_section = None
            for line in lines:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue

                # Detect section headers
                if "Patch Metrics" in line:
                    current_section = "patch_metrics"
                    continue
                elif "Class Metrics" in line:
                    current_section = "class_metrics"
                    continue
                elif "Landscape Metrics" in line:
                    current_section = "landscape_metrics"
                    continue

                # Parse metric data
                if current_section and '=' in line:
                    parts = line.split('=', 1)
                    if len(parts) == 2:
                        metric_name = parts[0].strip()
                        metric_value = parts[1].strip()

                        # Try to convert to numeric if possible
                        try:
                            if '.' in metric_value:
                                metric_value = float(metric_value)
                            else:
                                metric_value = int(metric_value)
                        except ValueError:
                            pass  # Keep as string

                        metrics[current_section][metric_name] = metric_value

        except Exception as e:
            logger.warning(f"Error parsing Fragstats output: {str(e)}")
            # Return raw content as fallback
            with open(output_file, 'r') as f:
                raw_content = f.read()
            metrics["raw_output"] = raw_content

        return metrics

    async def batch_process_multiple_maps(
        self,
        classified_rasters: List[str],
        parameters: Dict[str, Any] = None
    ) -> Dict[str, Any]:
        """
        Process multiple classified maps in batch mode.
        """
        if parameters is None:
            parameters = {}

        results = {}
        for i, raster in enumerate(classified_rasters):
            try:
                logger.info(f"Processing raster {i+1}/{len(classified_rasters)}: {raster}")
                raster_metrics = await self.calculate_landscape_metrics(raster, parameters)
                results[raster] = raster_metrics
            except Exception as e:
                logger.error(f"Failed to process {raster}: {str(e)}")
                results[raster] = {"error": str(e)}

        return {
            "batch_results": results,
            "total_processed": len([r for r in results.values() if "error" not in r]),
            "total_failed": len([r for r in results.values() if "error" in r]),
            "parameters_used": parameters
        }

# Singleton instance
fragstats_adapter = FragstatsAdapter()